INHERIT: ../zh/mkdocs.maybe-insiders.yml
site_name: FastAP-Channels
site_description: A FastAPI based websocket library - FastAPI-Channels
site_url: https://fc.bxzdyg.cn
site_author: BXZDYG
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
  - media: (prefers-color-scheme)
    toggle:
      icon: material/lightbulb-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to system preference
  features:
  - content.code.annotate
  - content.code.copy
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  - announce.dismiss
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: zh
  custom_dir: ../zh/overrides
repo_name: fastapi-channels
repo_url: https://github.com/YGuang233/fastapi-channels
markdown_extensions:
- abbr
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji ''
    emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
- pymdownx.highlight:
    line_spans: __span
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed:
    alternate_style: true
- admonition
- pymdownx.details
- mdx_include: null
plugins:
- git-revision-date-localized:
    type: date
    enable_creation_date: true
- git-committers:
    repository: YGuang233/fastapi-channels
    branch: master
- search
nav:
- 主页:
  - index.md
- 特点: features.md
- 学习:
  - learn/index.md
  - learn/setup.md
  - action:
    - learn/action.md
    - learn/limiter.md
- 开发者: people.md
- 参考:
  - resources/index.md
- 关于:
  - about/index.md
- 发行说明: release-notes.md
extra:
  analytics:
    provider: google
    property: G-RMREXXKJEQ
    feedback:
      title: 这个页面对你是否有帮助
      ratings:
      - icon: material/emoticon-happy-outline
        name: 这个页面很有帮助
        data: 1
        note: 感谢你的反馈!
      - icon: material/emoticon-sad-outline
        name: 此页面有待改进
        data: 0
        note: 感谢您的反馈！使用我们的<a href="..." target="_blank" rel="noopener">反馈表</a>.帮助我们改进此页面
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/yang
  - icon: fontawesome/brands/discord
    link: https://discord.gg/VQjSZaeJmf
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/fastapi
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/tiangolo
  - icon: fontawesome/brands/dev
    link: https://dev.to/tiangolo
  - icon: fontawesome/brands/medium
    link: https://medium.com/@tiangolo
  - icon: fontawesome/solid/globe
    link: https://blog.bxzdyg.cn
  alternate:
  - link: / # 之后要是添加不同的版本文档，这里绝对会出问题，因为路径像这样的： https://fc.bxzdyg.cn/0.1/en/why
    name: zh - 简体中文 #  而中文作为默认的话 https://fc.bxzdyg.cn/0.1/why why就变成了语言的位置存在冲突，
  - link: /en/ # 然后写一个绑定session的按钮可以设置每次进来重定向访问的语言
    name: en - English
  - link: /zh-hant/
    name: zh-hant - 繁體中文
  - link: /em/
    name: 😉
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- js/termynal.js
- js/custom.js
- js/fluff.js
copyright: Copyright &copy; 2024 BXZDYG
hooks:
- ../../scripts/mkdocs_hooks.py
